language: java

script: mvn clean package

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start

after_success:
  - mvn jacoco:report coveralls:report

jdk:
  - oraclejdk6

branches:
  only:
  - master

sudo: false

